---
abstract: 'Caching layer for DBIx::Class'
author:
  - 'Andrey Kostenko <andrey@kostenko.name>'
build_requires:
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.72'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: DBIx-Class-Storage-CacheProxy
no_index:
  directory:
    - inc
    - t
requires:
  Cache::Memcached: 0
  DBIx::Class: 0.08010
  Digest::SHA: 0
  Storable: 0
  parent: 0
  perl: 5.8.8
version: 0.01
